"""empty message

Revision ID: 88b790b9285c
Revises: 611e40aae03c
Create Date: 2020-01-05 21:59:16.760634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88b790b9285c'
down_revision = '611e40aae03c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question')
    )
    op.create_table('mobile_operator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('money_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('pin', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['operator'], ['mobile_operator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('firstname', sa.String(length=30), nullable=True),
    sa.Column('lastname', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('avartar', sa.String(), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('roles', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_code', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['roles'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('line_command',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.Column('command_name', sa.String(), nullable=False),
    sa.Column('command', sa.String(), nullable=False),
    sa.Column('command_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['money_line.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('command')
    )
    op.create_table('line_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('msg_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['money_line.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_float_cash',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone_id', sa.Integer(), nullable=True),
    sa.Column('starting_date', sa.DateTime(), nullable=False),
    sa.Column('starting_float', sa.Integer(), nullable=False),
    sa.Column('starting_cash', sa.Integer(), nullable=False),
    sa.Column('use_code', sa.String(), nullable=False),
    sa.Column('verifier_code', sa.String(length=60), nullable=False),
    sa.Column('verification', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['phone_id'], ['money_line.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trans_code', sa.String(), nullable=False),
    sa.Column('trans_date', sa.DateTime(), nullable=False),
    sa.Column('system_float_amount', sa.Integer(), nullable=False),
    sa.Column('user_float_amount', sa.Integer(), nullable=False),
    sa.Column('audited', sa.Boolean(), nullable=False),
    sa.Column('auditor_id', sa.Integer(), nullable=True),
    sa.Column('audit_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auditor_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trans_code')
    )
    op.create_table('transaction_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_id', sa.Integer(), nullable=False),
    sa.Column('trans_id', sa.Integer(), nullable=True),
    sa.Column('customer_phone', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('transaction_reason', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['phone_id'], ['money_line.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trans_id'], ['user_transaction.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_detail')
    op.drop_table('user_transaction')
    op.drop_table('user_float_cash')
    op.drop_table('line_message')
    op.drop_table('line_command')
    op.drop_table('history')
    op.drop_table('user')
    op.drop_table('money_line')
    op.drop_table('role')
    op.drop_table('mobile_operator')
    op.drop_table('faq')
    # ### end Alembic commands ###
